id: I63C79015
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:51:11+00:00'
last_modified: '2022-06-07T18:30:28.193816+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26741
  title: ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E29:
      image_group_id: I4169
      title: ''
      total_pages: 276
      order: 1
      base_file: 6E29.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
