id: P003226
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:42.490575
source_metadata:
  id: bdr:W26741
  title: ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    30a22e5cccd94cca83b2015513f39d3d:
      image_group_id: I4169
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
